version: "3"
services: 
  front:
    build: 
      context: "./front"
    image: "joellord/os-js-fs-front"
    ports: 
      - "80:8080"
  api:
    build: 
      context: "./server"
    image: "joellord/os-js-fs-api"
    environment: 
      NODE_PORT: "8080"
      CONN_STRING: "mysql://user:pass@database:3306/visits"
    ports: 
      - "80:8080"
  database:
    image: "joellord/os-js-fs-db"
    build: 
      context: "./database"
    volumes:
      - "db-data:/var/lib/mysql:rwx"
    ports:
      - "3306:3306"